### ISSUE TITLE
Support for tuples

### ISSUE THREAD

**Issue by bhough** [ForbesLindesay/tsgen#2]
Looks like `tsgen` doesn't currently support Flow's tuples type:

https://github.com/styled-components/polished/pull/238

Is this something that can be added?

**Comment by ForbesLindesay** [comment]
Yes, this should be a relatively simple fix.  If you want to have a go, start by adding a test case to:

https://github.com/ForbesLindesay/tsgen/tree/master/src/__test__

Then fix errors until the output looks like a typescript tuple (which is exactly the same syntax as a flow tuple)

**Comment by ForbesLindesay** [comment]
Fixed by f3e46a3253f94fa7b8a1704adc211dac480d3133
